name: presubmit
inputs:
  variant:
    required: true
  arch:
    required: true
runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0

    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    - uses: chainguard-images/actions/apko-build@5c3ba3d31d741657aa363519375e2331e8548317 # v1.0.9
      with:
        config: apko.yaml
        tag: quay.io/jetstack/${{ inputs.variant }}
        archs: ${{ inputs.arch }}

    - name: Load image from apko-produced tarball
      shell: bash
      run: |
        docker load < output.tar
