name: presubmit
inputs:
  variant:
    required: true
  arch:
    required: true
runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    - uses: chainguard-images/actions/apko-build@2b80d1c19318f71dba2624dcf611b87b886a81fb # v1.0.15
      with:
        config: apko.yaml
        tag: quay.io/jetstack/${{ inputs.variant }}
        archs: ${{ inputs.arch }}

    - name: Load image from apko-produced tarball
      shell: bash
      run: |
        docker load < output.tar
