name: presubmit
inputs:
  variant:
    required: true
  arch:
    required: true
runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    - uses: chainguard-images/actions/apko-build@8e701b320e7efcb120a1115de26e9fe833f86390 # v1.0.38
      with:
        config: apko.yaml
        tag: quay.io/jetstack/${{ inputs.variant }}
        archs: ${{ inputs.arch }}

    - name: Load image from apko-produced tarball
      shell: bash
      run: |
        docker load < output.tar
