name: release
inputs:
  variant:
    required: true
  username:
    required: true
  token:
    required: true
runs:
  using: composite
  steps:
    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    - uses: chainguard-images/actions/apko-snapshot@86c76897384d489bbd053726e796263dd9483d62 # v1.0.12
      with:
        config: apko.yaml
        archs: aarch64,armv7,ppc64le,x86_64,s390x
        registry: quay.io
        base-tag: quay.io/jetstack/${{ inputs.variant }}
        generic-user: ${{ inputs.username }}
        generic-pass: ${{ inputs.token }}
        username: ${{ inputs.username }}
        token: ${{ inputs.token }}
