name: release
inputs:
  variant:
    required: true
  archs:
    required: true
runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Populate workspace with variant source only
      shell: bash
      run: |
        shopt -s dotglob && tmp="$(mktemp -d)" && \
          mv ${{ inputs.variant }}/* ${tmp}/ && \
          mv .github ${tmp}/ && \
          rm -rf ./* && mv ${tmp}/* . && \
          echo ".github/" >> .melangeignore && tree -a . && \
          sudo rm -rf /work && sudo mkdir /work

    - uses: chainguard-images/actions/apko-snapshot@main
      with:
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}/${{ inputs.variant }}
        archs: ${{ inputs.archs }}
