name: base-csi-presubmit
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/actions/presubmit-variant/action.yml
      - .github/workflows/base-csi-presubmit.yml
      - base-csi/**
jobs:
  build:
    name: Verify base-csi image (single arch)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/presubmit-variant
        with:
          variant: base-csi
          archs: amd64
