name: base-csi
concurrency: base-csi
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - .github/actions/release-variant/action.yml
      - .github/workflows/base-csi.yml
      - base-csi/**
jobs:
  build:
    name: Release base-csi image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/release-variant
        with:
          variant: base-csi
          archs: amd64,aarch64,armv7
